version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mi-mongodb
    ports:
      - "27018:27018"
    volumes:
      - ./data/db:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      MONGODB_URI: 'mongodb://mongo:27018/nest'
    ports:
      - "3000:3000"
